Promise.resolve(60).then((val)=>{
    console.log(val);
    
}).catch(((err)=>{
    console.log(err);
    

}));